version = 1

exclude_patterns = [
    "public/**",
    "dist/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  dependency_file_paths = [
    "/",
    "client/"
  ]
  module_system = "es-modules"
  environment = [
    "nodejs",
    "browser",
    "jest",
    "mongo"
  ]
  style_guide = "airbnb"
  skip_doc_coverage = ["class-expression"]
